### ISSUE TITLE
Handling @online entry type

### ISSUE THREAD

**Issue by arifn** [RogerCrocker/BadaBib#1]
Hi, 
First of all, thank you for the great application. 

I opened my BibTeX file that has several `@online` entry types. Unfortunately, when I saved this file, these `@online` type references were missing. 

I also cannot add new `@online` entry types because they are not defined in the application. When I try to save further `@online` references, there is a window message showing:
>  Entries with empty keys in file xxx.bib

If you could do something about it, that will be very helpful. 

Thank you.

**Comment by RogerCrocker** [comment]
Hi! Thanks for the bug report, I can reproduce this issue.

The problem is that `@online` is a "non-standard" entry type, meaning it is defined in BibLaTeX, but not in standard BibTeX. BadaBib! is based on python-bibtexparser, which ignores non-standard entry types by default. 

python-bibtexparser does actually support non-standard entry types, I just didn't enable them since I rarely use/need them. But silently deleting non-standard entries is bad... In the long term, it would be nice to fully support BibLaTeX, but this will take some time. In the short term, given how common `@online` entries are, I think it would make sense to support only `@online` and just warn the user if the database contains any other non-standard entries. Would this work for you?

**Comment by arifn** [comment]
Yes, I think supporting non-standard type with a warning would be better. But you may also need to handle the pre-defined entry type in the Editor view. I do not know how much effort is required for this, though. 

Anyway, thank you.

**Comment by RogerCrocker** [comment]
OK, I added `@online` to the list of known entry types and enabled rudimentary support for non-standard entries. The latter can be modified in the editor, which falls back to the default layout. Currently this is `@article`, but it will hopefully be a user-defined setting in the future. In order to create non-standard entries, the BibTeX source needs to be edited directly. It's not perfect, but I think it's much better than ignoring and deleting entries.

Would you mind testing the current master branch? The easiest way is to clone the repository in GNOME Builder and just run the code. Otherwise I can update the flatpak within the next couple of days.

**Comment by arifn** [comment]
I do not have experience working with GNOME Builder. I will test it when you release it in the Flatpak. 
Thank you.

**Comment by RogerCrocker** [comment]
The new release should be out by now. Hope this solves the issue.

**Comment by arifn** [comment]
Apologies, I just got the chance to check today. 
All good. Thank you.
